name: Check if code can be run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 测试python代码是否能运行，主要是检查是否有语法错误等问题
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Run countdown_base.py
        run: |
          python python/countdown_base.py
          pyinstaller --onefile python/countdown_shell.py
          pyinstaller --onefile --windowed python/countdown_tkinter.py

      # 测试C#代码是否能编译
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Build C# project
        run: |
          cd "C#/CountdownShell/"
          dotnet build
          cd ../..
          cd "C#/CountdownAvalonia/"
          dotnet build
          cd ../..
      # 测试C++代码是否能编译
      - name: Install C++ dependencies
        run: |
          sudo apt-get update

      - name: Build C++ project
        run: |
          g++ -c "C++/countdown_shell.cpp"
